before_script:
  - sudo apt-get update
  - sudo apt-get install dart

stages:
  - build

webapp_build:
  stage: build
  tags:
    - www
  script:
    - pub get
    - pub build
    # Deploy
    - echo "DEPLOYMENT FOR BRANCH ${CI_COMMIT_REF_SLUG}"
    - mkdir -p /var/www/html/${CI_COMMIT_REF_SLUG}
    - cp -r build/web/* /var/www/html/${CI_COMMIT_REF_SLUG}
