before_script:
  - sudo apt-get update
  - sudo apt-get install dart

stages:
  - build

webapp_build:
  stage: build
  tags:
    - www
  script:
    - pub get
    - pub build
    # Deploy
    - echo "DEPLOYMENT FOR BRANCH ${CI_COMMIT_REF_NAME}" && pwd
    - echo ${CI_COMMIT_REF_NAME}
    - echo ${CI_COMMIT_REF_SLUG}
    - ls
    #- mkdir -p /var/www/html/${BRANCH_NAME}
    #- cp -r build/web/* /var/www/html/${BRANCH_NAME}
