before_script:
  - sudo apt-get update
  - sudo apt-get install dart

stages:
  - build
  - deploy

webapp_build:
  stage: build
  tags:
    - www
  script:
    - pub get
    - pub build

webapp_deploy:
  stage: deploy
  tags:
    - www
  script:
    # Save branch name in variable for later use
    - BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
    - echo "DEPLOYMENT FOR BRANCH ${BRANCH_NAME}" && pwd
    - ls
    - mkdir -p /var/www/html/${BRANCH_NAME}
    - cp -r build/web/* /var/www/html/${BRANCH_NAME}
