before_script:
  - sudo apt-get update
  - sudo apt-get install dart

stages:
  - build
  - deploy

webapp_build:
  stage: build
  tags:
    - www
  before-script:
    - pub get
  script:
    - pub build

webapp_deploy:
  stage: deploy
  tags:
    - www
  script:
    - echo "DEPLOYMENT NOT YET IMPLEMENTED"
