before_script:
  - sudo apt-get update
  - sudo apt-get install dart

stages:
  - build

webapp_build:
  stage: build
  tags:
    - www
  script:
    - pub upgrade
    - pub run build_runner build --release --output build
    # Deploy
    - echo "DEPLOYMENT FOR BRANCH ${CI_COMMIT_REF_SLUG}"
    - sudo mkdir -p /var/www/html/${CI_COMMIT_REF_SLUG}
    # Clean output folder
    - sudo rm -rf /var/www/html/${CI_COMMIT_REF_SLUG}/*
    # Copy build app to output folder
    - sudo cp -r build/web/* /var/www/html/${CI_COMMIT_REF_SLUG}
    # Replace base href because the base path is no more /
    - sudo sed -i 's:<base href="/">:<base href="/'${CI_COMMIT_REF_SLUG}'/">:g' /var/www/html/${CI_COMMIT_REF_SLUG}/index.html
    # Update version overview
    - /var/renew_version_html.sh --template /var/www/html/version/version_template.html --directory /var/www/html --target /var/www/html/version/index.html
