before_script:
  - sudo apt-get update
  - sudo apt-get install dart

stages:
  - build

webapp_build:
  stage: build
  tags:
    - www
  script:
    - pub get
    - pub build
    # Deploy
    - echo "DEPLOYMENT FOR BRANCH ${CI_COMMIT_REF_SLUG}"
    - sudo mkdir -p /var/www/html/${CI_COMMIT_REF_SLUG}
    - sudo cp -r build/web/* /var/www/html/${CI_COMMIT_REF_SLUG}
    # Replace base href because the base path is no more /
    - sed -i 's:<base href="/">:<base href="/'${CI_COMMIT_REF_SLUG}'/">:g' /var/www/html/${CI_COMMIT_REF_SLUG}/index.html
