name: hm_animations
description: A web app aiming at providing animations for students to enhance lecture learning effect.
version: 0.1.0
author: beder@hm.edu

environment:
  sdk: '>=2.0.0-dev.69.0 <2.0.0'

dependencies:
  angular: ^5.0.0-beta
  angular_components: ^0.9.0-beta
  angular_router: ^2.0.0-alpha

dev_dependencies:
  angular_test: ^2.0.0-beta
  build_runner: ^0.9.2
  build_test: ^0.10.3
  build_web_compilers: ^0.4.1
  test: ^1.3.0
  sass_builder: ^2.1.1