name: hm_animations
description: A web app aiming at providing animations for students to enhance lecture learning effect.
version: 2.4.1
author: beder@hm.edu

environment:
  sdk: '>=2.6.1 <3.0.0'

dependencies:
  angular: ^5.3.1
  angular_components: ^0.13.0+1
  angular_router: ^2.0.0-alpha
  angular_forms: ^2.1.2
  tuple: ^1.0.3
  vector_math: ^2.0.8
  dnd: ^1.4.2
  markdown: ^2.1.3

dev_dependencies:
  build_runner: ^1.7.2
  build_test: ^0.10.10
  build_web_compilers: ^2.7.1
  sass_builder: ^2.1.3
