name: hm_animations
description: A web app aiming at providing animations for students to enhance lecture learning effect.
version: 1.1.0
author: beder@hm.edu

environment:
  sdk: '>=2.1.0-dev.8.0 <3.0.0'

dependencies:
  angular: ^5.1.0
  angular_components: ^0.10.0
  angular_router: ^2.0.0-alpha
  angular_forms: ^2.1.0
  tuple: ^1.0.2
  vector_math: ^2.0.8

dev_dependencies:
  build_runner: ^1.0.0
  build_web_compilers: ^0.4.4
  sass_builder: ^2.1.2