name: hm_animations
description: A web app aiming at providing animations for students to enhance lecture learning effect.
version: 2.2.2
author: beder@hm.edu

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  angular: ^5.3.0
  angular_components: ^0.12.0
  angular_router: ^2.0.0-alpha
  angular_forms: ^2.1.1
  tuple: ^1.0.2
  vector_math: ^2.0.8
  dnd: ^1.4.2
  markdown: ^2.0.2

dev_dependencies:
  angular_test: ^2.2.0
  build_runner: ^1.1.2
  build_test: ^0.10.4
  build_web_compilers: ^1.0.0
  sass_builder: ^2.1.2
  test: ^1.5.1+1
