name: netzwerke_animationen
description: A web app aiming at providing animations for students to enhance lectures.
version: 0.0.1
author: beder@hm.edu

environment:
  sdk: '>=2.0.0-dev.48.0 <2.0.0'

dependencies:
  angular: ^5.0.0-alpha+11
  angular_components: ^0.9.0-alpha+11
  angular_router: ^2.0.0-alpha+11

dev_dependencies:
  angular_test: ^2.0.0-alpha
  build_runner: ^0.8.6
  build_test: ^0.10.2
  build_web_compilers: ^0.3.7
  test: ^0.12.30
  sass_builder: ^1.2.0
