name: netzwerke_animationen
description: A web app used to support students via animations in networking topics.
version: 0.0.1
author: beder@hm.edu
#homepage: https://www.example.com

environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:
  angular: ^4.0.0
  angular_components: ^0.8.0
  angular_router: ^1.0.2
  # Sass builder which is installed by angular components 0.8.0 is not working. Use 1.1.5 or newer! REMOVE THIS LINE ONCE THIS IS FIXED.
  sass_builder: ^1.1.5

dev_dependencies:
  angular_test: ^1.0.0
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  test: ^0.12.0

transformers:
- sass_builder
- angular:
    entry_points:
      - web/main.dart
      - test/**_test.dart
- test/pub_serve:
    $include: test/**_test.dart
- dart_to_js_script_rewriter

# Uncomment the following in sdk 1.24+ to make pub serve
# use dartdevc (webdev.dartlang.org/tools/dartdevc).
#web:
#  compiler:
#    debug: dartdevc
