name: hm_animations
description: A web app aiming at providing animations for students to enhance lecture learning effect.
version: 0.1.0
author: beder@hm.edu

environment:
  sdk: '>=2.0.0-dev.64.0 <2.0.0'

dependencies:
  angular: ^5.0.0-alpha
  angular_components: ^0.9.0-alpha
  angular_router: ^2.0.0-alpha
  sprintf: ^3.0.0

dev_dependencies:
  angular_test: ^2.0.0-alpha
  build_runner: ^0.8.10
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  test: ^1.0.0
  sass_builder: ^2.0.0